//! GENERATED by tools/gen_screen_rs.py from
//!   reports/screen_captures/club_staff.json  (sha256 7247d10cbbc97923)
//! DO NOT EDIT — rerun the generator instead. Hand-written code binds
//! dynamic state on top of this skeleton; it never re-types geometry.
#![allow(clippy::all)]

use crate::gen_screen_types::*;

pub const SLUG: &str = "club_staff";

pub fn screen() -> GenScreen {
    GenScreen {
        name: "club_staff",
        areas: vec![
            GenArea { id: 1, l: 100, t: 10, r: 790, b: 70, cnt_a: 1, w_a: 0, cnt_b: 1, w_b: 0, flags: 48, a10: 1, parent: -1, caller: 0 },
            GenArea { id: 2, l: 100, t: 25, r: 790, b: 55, cnt_a: 1, w_a: 0, cnt_b: 1, w_b: 0, flags: 1, a10: 1, parent: -1, caller: 0 },
            GenArea { id: 3, l: 110, t: 80, r: 780, b: 110, cnt_a: 1, w_a: 0, cnt_b: 1, w_b: 0, flags: 2, a10: 0, parent: -1, caller: 0 },
        ],
        objects: vec![
            GenObj { id: 4, ty: 1, l: 110, t: 515, r: 780, b: 545, a6: 0, a7: 0, rflags: 2, col_p: 0, col_s: 0, tflags: 12, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: -1 },
        ],
        tabs: vec![
        ],
        nav: vec![
            GenNav { back: 1, next: 0 },
        ],
        slots: vec![
        ],
    }
}
