//! GENERATED by tools/gen_screen_rs.py from
//!   reports/screen_captures/club_history.json  (sha256 f1bf0eb0b65576e1)
//! DO NOT EDIT — rerun the generator instead. Hand-written code binds
//! dynamic state on top of this skeleton; it never re-types geometry.
#![allow(clippy::all)]

use crate::gen_screen_types::*;

pub const SLUG: &str = "club_history";

pub fn screen() -> GenScreen {
    GenScreen {
        name: "club_history",
        areas: vec![
        ],
        objects: vec![
            GenObj { id: 1, ty: 1, l: 100, t: 10, r: 790, b: 70, a6: 0, a7: 0, rflags: 48, col_p: 9718863, col_s: 0, tflags: 12, font: 7, tmode: -1010580541, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: -1 },
        ],
        tabs: vec![
            GenTabStrip { count: 9, sel: 44, top_y_in: 80, bot_y_in: 545, split: 1, p4: 270499736, p5: 270499744 },
        ],
        nav: vec![
        ],
        slots: vec![
        ],
    }
}
