//! GENERATED by tools/gen_screen_rs.py from
//!   reports/screen_captures/club_overview.json  (sha256 dd22adc0bb2406d6)
//! DO NOT EDIT — rerun the generator instead. Hand-written code binds
//! dynamic state on top of this skeleton; it never re-types geometry.
#![allow(clippy::all)]

use crate::gen_screen_types::*;

pub const SLUG: &str = "club_overview";

pub fn screen() -> GenScreen {
    GenScreen {
        name: "club_overview",
        areas: vec![
            GenArea { id: 3, l: 110, t: 145, r: 780, b: 535, cnt_a: 4, w_a: 270499664, cnt_b: 17, w_b: 0, flags: 2, a10: 0, parent: -1, caller: 0 },
            GenArea { id: 4, l: 100, t: 555, r: 790, b: 590, cnt_a: 2, w_a: 270499618, cnt_b: 1, w_b: 0, flags: 1, a10: 0, parent: -1, caller: 0 },
        ],
        objects: vec![
            GenObj { id: 1, ty: 1, l: 100, t: 10, r: 790, b: 70, a6: 0, a7: 0, rflags: 48, col_p: 0, col_s: 0, tflags: 12, font: 7, tmode: 0, text_ptr: 49, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: -1 },
            GenObj { id: 2, ty: 1, l: 100, t: 80, r: 790, b: 125, a6: 0, a7: 0, rflags: 2, col_p: 0, col_s: 0, tflags: 12, font: 6, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: -1 },
            GenObj { id: 5, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 48, col_p: -65536, col_s: -65536, tflags: 12, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 2, a17: 0, parent: 4 },
            GenObj { id: 6, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 0, rflags: 48, col_p: 0, col_s: 0, tflags: 44, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 4 },
        ],
        tabs: vec![
        ],
        nav: vec![
        ],
        slots: vec![
        ],
    }
}
