//! GENERATED by tools/gen_screen_rs.py from
//!   reports/screen_captures/competition_league.json  (sha256 0af04d7201ebf784)
//! DO NOT EDIT — rerun the generator instead. Hand-written code binds
//! dynamic state on top of this skeleton; it never re-types geometry.
#![allow(clippy::all)]

use crate::gen_screen_types::*;

pub const SLUG: &str = "competition_league";

pub fn screen() -> GenScreen {
    GenScreen {
        name: "competition_league",
        areas: vec![
            GenArea { id: 3, l: 0, t: 0, r: 0, b: 0, cnt_a: 0, w_a: 0, cnt_b: 0, w_b: 0, flags: 304, a10: 0, parent: 2, caller: 0 },
        ],
        objects: vec![
            GenObj { id: 1, ty: 1, l: 100, t: 10, r: 790, b: 70, a6: 0, a7: 0, rflags: 48, col_p: 274726912, col_s: 0, tflags: 12, font: 7, tmode: 274726912, text_ptr: -1010580537, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: -1 },
            GenObj { id: 2, ty: 2, l: 710, t: 15, r: 785, b: 35, a6: 0, a7: 0, rflags: 48, col_p: 1, col_s: 1, tflags: 12, font: 1, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: -1 },
            GenObj { id: 4, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 0, col_s: 0, tflags: 1, font: 1, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 25, a17: 1, parent: 3 },
            GenObj { id: 5, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 0, col_s: -1010630656, tflags: 1, font: 1, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 25, a17: 2, parent: 3 },
            GenObj { id: 6, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: -1010630656, col_s: 0, tflags: 1, font: 1, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 25, a17: 4, parent: 3 },
            GenObj { id: 7, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 0, col_s: 0, tflags: 1, font: 1, tmode: -1010630656, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 25, a17: 8, parent: 3 },
            GenObj { id: 8, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 0, col_s: -1010630656, tflags: 1, font: 1, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 25, a17: 16, parent: 3 },
            GenObj { id: 9, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: -1010630656, col_s: 0, tflags: 1, font: 1, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 25, a17: 31, parent: 3 },
        ],
        tabs: vec![
            GenTabStrip { count: 10, sel: 0, top_y_in: 80, bot_y_in: 545, split: 0, p4: 270499168, p5: 270499164 },
        ],
        nav: vec![
        ],
        slots: vec![
            GenSlot { idx: 52, val: 0, kind: 0 },
        ],
    }
}
