//! GENERATED by tools/gen_screen_rs.py from
//!   reports/screen_captures/game_settings_live.json  (sha256 25d340c7cba0b19f)
//! DO NOT EDIT — rerun the generator instead. Hand-written code binds
//! dynamic state on top of this skeleton; it never re-types geometry.
#![allow(clippy::all)]

use crate::gen_screen_types::*;

pub const SLUG: &str = "game_settings_live";

pub fn screen() -> GenScreen {
    GenScreen {
        name: "game_settings_live",
        areas: vec![
            GenArea { id: 1, l: 0, t: 0, r: 799, b: 599, cnt_a: 1, w_a: 0, cnt_b: 1, w_b: 0, flags: 2, a10: 0, parent: -1, caller: 8441300 },
            GenArea { id: 2, l: 145, t: 50, r: 744, b: 549, cnt_a: 1, w_a: 0, cnt_b: 1, w_b: 0, flags: 48, a10: 448, parent: -1, caller: 8441398 },
            GenArea { id: 6, l: 155, t: 509, r: 734, b: 539, cnt_a: 2, w_a: 1700834, cnt_b: 1, w_b: 0, flags: 1, a10: 0, parent: -1, caller: 8441810 },
            GenArea { id: 28, l: 170, t: 150, r: 719, b: 484, cnt_a: 5, w_a: 1700840, cnt_b: 15, w_b: 0, flags: 1, a10: 0, parent: -1, caller: 8442146 },
            GenArea { id: 31, l: 0, t: 0, r: 0, b: 0, cnt_a: 0, w_a: 0, cnt_b: 0, w_b: 0, flags: 1048624, a10: -64512, parent: 25, caller: 8442380 },
            GenArea { id: 41, l: 0, t: 0, r: 0, b: 0, cnt_a: 0, w_a: 0, cnt_b: 0, w_b: 0, flags: 1048624, a10: 1024, parent: 34, caller: 8443049 },
            GenArea { id: 70, l: 0, t: 0, r: 0, b: 0, cnt_a: 0, w_a: 0, cnt_b: 0, w_b: 0, flags: 1048624, a10: 1024, parent: 62, caller: 8443604 },
        ],
        objects: vec![
            GenObj { id: 3, ty: 1, l: 155, t: 60, r: 734, b: 105, a6: 0, a7: 0, rflags: 48, col_p: 14417920, col_s: 0, tflags: 12, font: 4, tmode: 14477084, text_ptr: 14447164, text: "Game Settings", caller: 8441503, a15: 0, a16: 0, a17: 0, parent: -1 },
            GenObj { id: 4, ty: 1, l: 165, t: 115, r: 555, b: 135, a6: 0, a7: 0, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 1, tmode: 14468632, text_ptr: 14447164, text: "Version: 3.9.60 - Build: Sep 24 2001 15:00:49", caller: 8441650, a15: 0, a16: 0, a17: 0, parent: -1 },
            GenObj { id: 5, ty: 2, l: 609, t: 115, r: 734, b: 135, a6: 0, a7: 0, rflags: 48, col_p: -31728, col_s: -31728, tflags: 12, font: 1, tmode: 14477084, text_ptr: 14447164, text: "Reset", caller: 8441754, a15: 0, a16: 39, a17: 0, parent: -1 },
            GenObj { id: 7, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 48, col_p: -31728, col_s: -31728, tflags: 12, font: 3, tmode: 14477084, text_ptr: 14447164, text: "Cancel", caller: 8441911, a15: 0, a16: 40, a17: 0, parent: 2 },
            GenObj { id: 8, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 0, rflags: 48, col_p: -31728, col_s: -31728, tflags: 12, font: 3, tmode: 14477084, text_ptr: 14447164, text: "Ok", caller: 8442010, a15: 0, a16: 41, a17: 0, parent: 2 },
            GenObj { id: 9, ty: 1, l: 165, t: 145, r: 724, b: 489, a6: 0, a7: 0, rflags: 112, col_p: 512, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9014627, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 10, ty: 1, l: 166, t: 194, r: 723, b: 243, a6: 0, a7: 0, rflags: 16, col_p: 448, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9014773, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 11, ty: 1, l: 166, t: 292, r: 723, b: 341, a6: 0, a7: 0, rflags: 16, col_p: -1227161152, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9014911, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 12, ty: 1, l: 166, t: 390, r: 723, b: 439, a6: 0, a7: 0, rflags: 16, col_p: 448, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9015035, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 13, ty: 1, l: 173, t: 153, r: 716, b: 481, a6: 0, a7: 0, rflags: 544, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9015231, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 14, ty: 1, l: 445, t: 153, r: 445, b: 481, a6: 0, a7: 0, rflags: 1024, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9015307, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 15, ty: 1, l: 405, t: 277, r: 485, b: 357, a6: 0, a7: 0, rflags: 65568, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 640, text_ptr: 0, text: "", caller: 9015443, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 16, ty: 1, l: 181, t: 277, r: 261, b: 357, a6: 0, a7: 0, rflags: 65568, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 640, text_ptr: 0, text: "", caller: 9015546, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 17, ty: 1, l: 181, t: 277, r: 244, b: 357, a6: 0, a7: 0, rflags: 16, col_p: 512, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9015660, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 18, ty: 1, l: 181, t: 292, r: 244, b: 341, a6: 0, a7: 0, rflags: 16, col_p: 448, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9015757, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 19, ty: 1, l: 221, t: 317, r: 221, b: 317, a6: 0, a7: 0, rflags: 1024, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9015843, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 20, ty: 1, l: 173, t: 277, r: 197, b: 357, a6: 0, a7: 0, rflags: 544, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9015951, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 21, ty: 1, l: 173, t: 229, r: 245, b: 405, a6: 0, a7: 0, rflags: 544, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9016080, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 22, ty: 1, l: 628, t: 277, r: 708, b: 357, a6: 0, a7: 0, rflags: 65568, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 640, text_ptr: 0, text: "", caller: 9016170, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 23, ty: 1, l: 645, t: 277, r: 708, b: 357, a6: 0, a7: 0, rflags: 16, col_p: 512, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9016266, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 24, ty: 1, l: 645, t: 292, r: 708, b: 341, a6: 0, a7: 0, rflags: 16, col_p: 448, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9016363, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 25, ty: 1, l: 668, t: 317, r: 668, b: 317, a6: 0, a7: 0, rflags: 1024, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9016436, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 26, ty: 1, l: 692, t: 277, r: 716, b: 357, a6: 0, a7: 0, rflags: 544, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9016517, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 27, ty: 1, l: 644, t: 229, r: 716, b: 405, a6: 0, a7: 0, rflags: 544, col_p: 640, col_s: 0, tflags: 0, font: 0, tmode: 0, text_ptr: 0, text: "", caller: 9016605, a15: 0, a16: 0, a17: 0, parent: 2 },
            GenObj { id: 29, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 3, tmode: 14468632, text_ptr: 14447164, text: " Language", caller: 8442237, a15: 0, a16: 0, a17: 0, parent: 3 },
            GenObj { id: 30, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 2, a7: 0, rflags: 48, col_p: 2006908928, col_s: 2006908928, tflags: 12, font: 1, tmode: -6372, text_ptr: 0, text: "", caller: 8442325, a15: 0, a16: 0, a17: 0, parent: 3 },
            GenObj { id: 32, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 0, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 2, tmode: 65504, text_ptr: 14447164, text: "  English", caller: 8442621, a15: 0, a16: 0, a17: 0, parent: 3 },
            GenObj { id: 33, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 65504, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "English", caller: 8442773, a15: 0, a16: 42, a17: 0, parent: 4 },
            GenObj { id: 34, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 65504, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Italiano", caller: 8442773, a15: 0, a16: 42, a17: 4, parent: 4 },
            GenObj { id: 35, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 65504, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Dansk", caller: 8442773, a15: 0, a16: 42, a17: 6, parent: 4 },
            GenObj { id: 36, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 65504, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Norsk", caller: 8442773, a15: 0, a16: 42, a17: 8, parent: 4 },
            GenObj { id: 37, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 65504, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Portugu", caller: 8442773, a15: 0, a16: 42, a17: 9, parent: 4 },
            GenObj { id: 38, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 65504, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Svenska", caller: 8442773, a15: 0, a16: 42, a17: 10, parent: 4 },
            GenObj { id: 39, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 1, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 3, tmode: 14468632, text_ptr: 14447164, text: " Currency", caller: 8442890, a15: 0, a16: 0, a17: 0, parent: 3 },
            GenObj { id: 40, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 2, a7: 1, rflags: 48, col_p: 10289152, col_s: 10289152, tflags: 12, font: 1, tmode: 59164, text_ptr: 0, text: "", caller: 8442986, a15: 0, a16: 0, a17: 0, parent: 3 },
            GenObj { id: 42, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 1, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 2, tmode: 1703904, text_ptr: 14447164, text: "  ", caller: 8443259, a15: 0, a16: 0, a17: 0, parent: 3 },
            GenObj { id: 43, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 65504, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "", caller: 8443344, a15: 0, a16: 43, a17: 0, parent: 5 },
            GenObj { id: 44, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Peso", caller: 8443344, a15: 0, a16: 43, a17: 1, parent: 5 },
            GenObj { id: 45, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Aus$", caller: 8443344, a15: 0, a16: 43, a17: 2, parent: 5 },
            GenObj { id: 46, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "BFr", caller: 8443344, a15: 0, a16: 43, a17: 3, parent: 5 },
            GenObj { id: 47, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Real", caller: 8443344, a15: 0, a16: 43, a17: 4, parent: 5 },
            GenObj { id: 48, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Kuna", caller: 8443344, a15: 0, a16: 43, a17: 5, parent: 5 },
            GenObj { id: 49, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "DKr", caller: 8443344, a15: 0, a16: 43, a17: 6, parent: 5 },
            GenObj { id: 50, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Euro", caller: 8443344, a15: 0, a16: 43, a17: 7, parent: 5 },
            GenObj { id: 51, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Markka", caller: 8443344, a15: 0, a16: 43, a17: 8, parent: 5 },
            GenObj { id: 52, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "FFr", caller: 8443344, a15: 0, a16: 43, a17: 9, parent: 5 },
            GenObj { id: 53, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "DM", caller: 8443344, a15: 0, a16: 43, a17: 10, parent: 5 },
            GenObj { id: 54, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "DFl", caller: 8443344, a15: 0, a16: 43, a17: 11, parent: 5 },
            GenObj { id: 55, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Drachma", caller: 8443344, a15: 0, a16: 43, a17: 12, parent: 5 },
            GenObj { id: 56, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "IR", caller: 8443344, a15: 0, a16: 43, a17: 13, parent: 5 },
            GenObj { id: 57, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Lira", caller: 8443344, a15: 0, a16: 43, a17: 14, parent: 5 },
            GenObj { id: 58, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "", caller: 8443344, a15: 0, a16: 43, a17: 15, parent: 5 },
            GenObj { id: 59, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "NKr", caller: 8443344, a15: 0, a16: 43, a17: 16, parent: 5 },
            GenObj { id: 60, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Zloty", caller: 8443344, a15: 0, a16: 43, a17: 17, parent: 5 },
            GenObj { id: 61, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Escudo", caller: 8443344, a15: 0, a16: 43, a17: 18, parent: 5 },
            GenObj { id: 62, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Ruble", caller: 8443344, a15: 0, a16: 43, a17: 19, parent: 5 },
            GenObj { id: 63, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "Pta", caller: 8443344, a15: 0, a16: 43, a17: 20, parent: 5 },
            GenObj { id: 64, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "SKr", caller: 8443344, a15: 0, a16: 43, a17: 21, parent: 5 },
            GenObj { id: 65, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "SwF", caller: 8443344, a15: 0, a16: 43, a17: 22, parent: 5 },
            GenObj { id: 66, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "TLira", caller: 8443344, a15: 0, a16: 43, a17: 23, parent: 5 },
            GenObj { id: 67, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 16, col_p: 1639424, col_s: 274857952, tflags: 1, font: 1, tmode: 0, text_ptr: 1700876, text: "$", caller: 8443344, a15: 0, a16: 43, a17: 24, parent: 5 },
            GenObj { id: 68, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 2, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 3, tmode: 14468632, text_ptr: 14447164, text: " Fonts", caller: 8443454, a15: 0, a16: 0, a17: 0, parent: 3 },
            GenObj { id: 69, ty: 2, l: 0, t: 0, r: 0, b: 0, a6: 2, a7: 2, rflags: 48, col_p: 10289152, col_s: 10289152, tflags: 12, font: 1, tmode: 59164, text_ptr: 0, text: "", caller: 8443541, a15: 0, a16: 0, a17: 0, parent: 3 },
        ],
        tabs: vec![
        ],
        nav: vec![
        ],
        slots: vec![
        ],
    }
}
