//! GENERATED by tools/gen_screen_rs.py — module list + registry.
//! DO NOT EDIT; rerun the generator to refresh.

use crate::gen_screen_types::GenScreen;

pub mod club_history;
pub mod club_overview;
pub mod club_squad_live;
pub mod club_staff;
pub mod competition_league;
pub mod dashboard;
pub mod fifa_rankings_live;
pub mod game_settings_live;
pub mod manager_profile_live;
pub mod manager_stats_live;
pub mod news;
pub mod news_live;
pub mod player_overview;
pub mod player_profile_live;
pub mod player_search_live;
pub mod select_league;
pub mod select_league_live;
pub mod tactics;
pub mod transfers_live;
pub mod wc_euro_qual_live;

/// Look up a generated screen by its capture slug.
pub fn lookup(slug: &str) -> Option<fn() -> GenScreen> {
    match slug {
        club_history::SLUG => Some(club_history::screen),
        club_overview::SLUG => Some(club_overview::screen),
        club_squad_live::SLUG => Some(club_squad_live::screen),
        club_staff::SLUG => Some(club_staff::screen),
        competition_league::SLUG => Some(competition_league::screen),
        dashboard::SLUG => Some(dashboard::screen),
        fifa_rankings_live::SLUG => Some(fifa_rankings_live::screen),
        game_settings_live::SLUG => Some(game_settings_live::screen),
        manager_profile_live::SLUG => Some(manager_profile_live::screen),
        manager_stats_live::SLUG => Some(manager_stats_live::screen),
        news::SLUG => Some(news::screen),
        news_live::SLUG => Some(news_live::screen),
        player_overview::SLUG => Some(player_overview::screen),
        player_profile_live::SLUG => Some(player_profile_live::screen),
        player_search_live::SLUG => Some(player_search_live::screen),
        select_league::SLUG => Some(select_league::screen),
        select_league_live::SLUG => Some(select_league_live::screen),
        tactics::SLUG => Some(tactics::screen),
        transfers_live::SLUG => Some(transfers_live::screen),
        wc_euro_qual_live::SLUG => Some(wc_euro_qual_live::screen),
        _ => None,
    }
}

/// All generated slugs, for --list.
pub fn all_slugs() -> &'static [&'static str] {
    &[
        club_history::SLUG,
        club_overview::SLUG,
        club_squad_live::SLUG,
        club_staff::SLUG,
        competition_league::SLUG,
        dashboard::SLUG,
        fifa_rankings_live::SLUG,
        game_settings_live::SLUG,
        manager_profile_live::SLUG,
        manager_stats_live::SLUG,
        news::SLUG,
        news_live::SLUG,
        player_overview::SLUG,
        player_profile_live::SLUG,
        player_search_live::SLUG,
        select_league::SLUG,
        select_league_live::SLUG,
        tactics::SLUG,
        transfers_live::SLUG,
        wc_euro_qual_live::SLUG,
    ]
}
