//! GENERATED by tools/gen_screen_rs.py from
//!   reports/screen_captures/news.json  (sha256 89fff07048b77686)
//! DO NOT EDIT — rerun the generator instead. Hand-written code binds
//! dynamic state on top of this skeleton; it never re-types geometry.
#![allow(clippy::all)]

use crate::gen_screen_types::*;

pub const SLUG: &str = "news";

pub fn screen() -> GenScreen {
    GenScreen {
        name: "news",
        areas: vec![
            GenArea { id: 1, l: 100, t: 10, r: 790, b: 70, cnt_a: 1, w_a: 0, cnt_b: 1, w_b: 0, flags: 48, a10: 1, parent: -1, caller: 0 },
            GenArea { id: 2, l: 100, t: 25, r: 790, b: 55, cnt_a: 1, w_a: 0, cnt_b: 1, w_b: 0, flags: 1, a10: 0, parent: -1, caller: 0 },
        ],
        objects: vec![
            GenObj { id: 3, ty: 1, l: 100, t: 10, r: 790, b: 70, a6: 0, a7: 0, rflags: 48, col_p: 1, col_s: 0, tflags: 12, font: 7, tmode: 1, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: -1 },
        ],
        tabs: vec![
            GenTabStrip { count: 8, sel: 12, top_y_in: 80, bot_y_in: 545, split: 1, p4: 270499516, p5: 270499596 },
        ],
        nav: vec![
        ],
        slots: vec![
            GenSlot { idx: 0, val: 0, kind: 0 },
            GenSlot { idx: 2, val: 1, kind: 0 },
            GenSlot { idx: 3, val: 3, kind: 0 },
        ],
    }
}
