//! GENERATED by tools/gen_screen_rs.py from
//!   reports/screen_captures/select_league.json  (sha256 187297d8fd367386)
//! DO NOT EDIT — rerun the generator instead. Hand-written code binds
//! dynamic state on top of this skeleton; it never re-types geometry.
#![allow(clippy::all)]

use crate::gen_screen_types::*;

pub const SLUG: &str = "select_league";

pub fn screen() -> GenScreen {
    GenScreen {
        name: "select_league",
        areas: vec![
        ],
        objects: vec![
            GenObj { id: 1, ty: 1, l: 100, t: 10, r: 790, b: 70, a6: 0, a7: 0, rflags: 48, col_p: 11862016, col_s: 0, tflags: 12, font: 7, tmode: 0, text_ptr: 14402432, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: -1 },
            GenObj { id: 2, ty: 1, l: 100, t: 80, r: 790, b: 125, a6: 0, a7: 0, rflags: 2, col_p: 0, col_s: 0, tflags: 12, font: 6, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: -1 },
            GenObj { id: 3, ty: 2, l: 100, t: 555, r: 790, b: 590, a6: 0, a7: 0, rflags: 48, col_p: 0, col_s: 0, tflags: 12, font: 4, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 52, a17: 0, parent: -1 },
        ],
        tabs: vec![
        ],
        nav: vec![
        ],
        slots: vec![
        ],
    }
}
