//! GENERATED by tools/gen_screen_rs.py from
//!   reports/screen_captures/tactics.json  (sha256 11c4a661e3ff3a84)
//! DO NOT EDIT — rerun the generator instead. Hand-written code binds
//! dynamic state on top of this skeleton; it never re-types geometry.
#![allow(clippy::all)]

use crate::gen_screen_types::*;

pub const SLUG: &str = "tactics";

pub fn screen() -> GenScreen {
    GenScreen {
        name: "tactics",
        areas: vec![
            GenArea { id: 1, l: 0, t: 0, r: 799, b: 599, cnt_a: 1, w_a: 0, cnt_b: 1, w_b: 0, flags: 2, a10: 0, parent: -1, caller: 0 },
            GenArea { id: 2, l: 170, t: 55, r: 719, b: 544, cnt_a: 1, w_a: 0, cnt_b: 1, w_b: 0, flags: 48, a10: 276832256, parent: -1, caller: 0 },
            GenArea { id: 4, l: 180, t: 504, r: 709, b: 534, cnt_a: 2, w_a: 270497182, cnt_b: 1, w_b: 0, flags: 1, a10: 0, parent: -1, caller: 0 },
            GenArea { id: 6, l: 195, t: 135, r: 694, b: 479, cnt_a: 5, w_a: 270497068, cnt_b: 7, w_b: 0, flags: 1, a10: 0, parent: -1, caller: 0 },
        ],
        objects: vec![
            GenObj { id: 3, ty: 1, l: 180, t: 65, r: 709, b: 110, a6: 0, a7: 0, rflags: 48, col_p: 0, col_s: 0, tflags: 12, font: 4, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: -1 },
            GenObj { id: 5, ty: 2, l: 180, t: 504, r: 709, b: 534, a6: 0, a7: 0, rflags: 48, col_p: 0, col_s: 0, tflags: 12, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 2, a17: 0, parent: -1 },
            GenObj { id: 7, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 0, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 8, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 0, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 9, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 2, a7: 0, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 10, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 3, a7: 0, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 11, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 1, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 12, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 1, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 13, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 2, a7: 1, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 14, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 3, a7: 1, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 15, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 4, a7: 1, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 16, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 2, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 17, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 2, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 18, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 2, a7: 2, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 19, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 3, a7: 2, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 20, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 3, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 21, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 3, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 22, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 2, a7: 3, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 23, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 4, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 24, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 4, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 25, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 2, a7: 4, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 26, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 5, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 27, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 5, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 28, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 2, a7: 5, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 29, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 0, a7: 6, rflags: 1, col_p: 0, col_s: 0, tflags: 1, font: 3, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 30, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 1, a7: 6, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
            GenObj { id: 31, ty: 1, l: 0, t: 0, r: 0, b: 0, a6: 2, a7: 6, rflags: 1, col_p: 0, col_s: 0, tflags: 12, font: 2, tmode: 0, text_ptr: 14447164, text: "", caller: 0, a15: 0, a16: 0, a17: 0, parent: 6 },
        ],
        tabs: vec![
        ],
        nav: vec![
        ],
        slots: vec![
        ],
    }
}
