"""Generate Rust screen-geometry modules from exe ground-truth captures.

This script is the anti-drift layer: every static coordinate, flag, and font
id in the Rust GUI port flows  capture JSON -> this script -> generated .rs
with no hand transcription anywhere. Hand-written code binds dynamic game
state on top of the generated skeleton; it never re-types geometry.

Pipeline:
  1) python tools/capture_all_screens.py <slug>
        -> reports/screen_captures/<slug>.json        (exe ground truth)
  2) python tools/gen_screen_rs.py <slug>|--all
        -> crates/cm-render/src/gen_screens/<name>.rs (generated, DO NOT EDIT)
        -> crates/cm-render/src/gen_screens/mod.rs    (regenerated registry)
  3) cargo run -p cm-render --bin dump_screen_geometry -- --gen <slug>
        -> reports/screen_captures/<slug>.render.json
  4) python tools/diff_screens.py <slug>
        -> exit 0 iff every widget matches

--all generates every geometry-bearing capture (one with at least one area,
object, or tab). Slot-only captures (setup-fn traces with no widgets) are
skipped with a note: they are inputs for View slot maps, not screens.
"""
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CAPTURES = REPO / "reports" / "screen_captures"
GEN_DIR = REPO / "crates" / "cm-render" / "src" / "gen_screens"

HEADER = """\
//! GENERATED by tools/gen_screen_rs.py from
//!   reports/screen_captures/{slug}.json  (sha256 {sha})
//! DO NOT EDIT — rerun the generator instead. Hand-written code binds
//! dynamic state on top of this skeleton; it never re-types geometry.
#![allow(clippy::all)]

use crate::gen_screen_types::*;
"""


def rust_ident(slug: str) -> str:
    ident = re.sub(r"[^a-z0-9_]", "_", slug.lower())
    if ident[0].isdigit():
        ident = "s_" + ident
    return ident


def geometry_bearing(d: dict) -> bool:
    return bool(d.get("areas") or d.get("objects") or d.get("tabs") or d.get("nav"))


def require(rec: dict, key, where: str):
    """Fail loudly on schema drift instead of silently defaulting."""
    if key not in rec:
        sys.exit(f"schema error: missing {key!r} in {where}: {rec}")
    return rec[key]


def obj_text(rec: dict) -> str:
    """Live-capture text for an object, if any.

    text_hex (raw bytes, current live script): decode latin-1, cut at NUL.
    text_str (first live run, mangled by readCString's UTF-8 decode): the
    real string is the printable prefix before the first replacement char —
    a heuristic that holds for ASCII labels; non-ASCII tails were lost in
    that run and recover on the next capture. Emulation captures have
    neither field -> empty.
    """
    hx = rec.get("text_hex")
    if hx:
        b = bytes.fromhex(hx).split(b"\x00", 1)[0]
        return b.decode("latin-1", "replace")
    t = rec.get("text_str")
    if not t:
        return ""
    for i, c in enumerate(t):
        if c == "�" or ord(c) < 9:
            return t[:i]
    return t


def gen_module(slug: str) -> str:
    src = CAPTURES / f"{slug}.json"
    if not src.exists():
        sys.exit(f"missing capture: {src}")
    raw = src.read_bytes()
    d = json.loads(raw)
    sha = hashlib.sha256(raw).hexdigest()[:16]
    out = [HEADER.format(slug=slug, sha=sha)]
    out.append("pub fn screen() -> GenScreen {")
    out.append("    GenScreen {")
    out.append(f"        name: {json.dumps(slug)},")

    out.append("        areas: vec![")
    for a in d["areas"]:
        w = f"{slug}.areas"
        out.append(
            "            GenArea { "
            f"id: {require(a,'id',w)}, "
            f"l: {require(a,'L',w)}, t: {require(a,'T',w)}, "
            f"r: {require(a,'R',w)}, b: {require(a,'B',w)}, "
            f"cnt_a: {require(a,'cntA',w)}, w_a: {require(a,'wA',w)}, "
            f"cnt_b: {require(a,'cntB',w)}, w_b: {require(a,'wB',w)}, "
            f"flags: {require(a,'flags',w)}, a10: {require(a,'a10',w)}, "
            f"parent: {require(a,'parent',w)}, "
            f"caller: {int(str(a.get('caller', '0x0')), 16)} }},"
        )
    out.append("        ],")

    out.append("        objects: vec![")
    for o in d["objects"]:
        w = f"{slug}.objects"
        out.append(
            "            GenObj { "
            f"id: {require(o,'id',w)}, ty: {require(o,'type',w)}, "
            f"l: {require(o,'L',w)}, t: {require(o,'T',w)}, "
            f"r: {require(o,'R',w)}, b: {require(o,'B',w)}, "
            f"a6: {require(o,'a6',w)}, a7: {require(o,'a7',w)}, "
            f"rflags: {require(o,'rflags',w)}, "
            f"col_p: {require(o,'colP',w)}, col_s: {require(o,'colS',w)}, "
            f"tflags: {require(o,'tflags',w)}, font: {require(o,'font',w)}, "
            f"tmode: {require(o,'tmode',w)}, text_ptr: {require(o,'text',w)}, "
            f"text: {json.dumps(obj_text(o))}, "
            f"caller: {int(str(o.get('caller', '0x0')), 16)}, "
            f"a15: {require(o,'a15',w)}, a16: {require(o,'a16',w)}, "
            f"a17: {require(o,'a17',w)}, parent: {require(o,'parent',w)} }},"
        )
    out.append("        ],")

    out.append("        tabs: vec![")
    for t in d["tabs"]:
        w = f"{slug}.tabs"
        out.append(
            "            GenTabStrip { "
            f"count: {require(t,'count',w)}, sel: {require(t,'sel',w)}, "
            f"top_y_in: {require(t,'top_y_in',w)}, "
            f"bot_y_in: {require(t,'bot_y_in',w)}, "
            f"split: {require(t,'split',w)}, "
            f"p4: {require(t,'p4',w)}, p5: {require(t,'p5',w)} }},"
        )
    out.append("        ],")

    out.append("        nav: vec![")
    for n in d["nav"]:
        w = f"{slug}.nav"
        out.append(
            "            GenNav { "
            f"back: {require(n,'back',w)}, next: {require(n,'next',w)} }},"
        )
    out.append("        ],")

    out.append("        slots: vec![")
    for s in d["slots"]:
        w = f"{slug}.slots"
        out.append(
            "            GenSlot { "
            f"idx: {require(s,'idx',w)}, val: {require(s,'val',w)}, "
            f"kind: {require(s,'kind',w)} }},"
        )
    out.append("        ],")
    out.append("    }")
    out.append("}")
    out.append("")
    return "\n".join(out)


def regen_mod_rs():
    mods = sorted(
        p.stem for p in GEN_DIR.glob("*.rs") if p.stem != "mod"
    )
    lines = [
        "//! GENERATED by tools/gen_screen_rs.py — module list + registry.",
        "//! DO NOT EDIT; rerun the generator to refresh.",
        "",
        "use crate::gen_screen_types::GenScreen;",
        "",
    ]
    for m in mods:
        lines.append(f"pub mod {m};")
    lines += [
        "",
        "/// Look up a generated screen by its capture slug.",
        "pub fn lookup(slug: &str) -> Option<fn() -> GenScreen> {",
        "    match slug {",
    ]
    for m in mods:
        # The module knows its own slug; key by both slug and ident.
        lines.append(f"        {m}::SLUG => Some({m}::screen),")
    lines += [
        "        _ => None,",
        "    }",
        "}",
        "",
        "/// All generated slugs, for --list.",
        "pub fn all_slugs() -> &'static [&'static str] {",
        "    &[",
    ]
    for m in mods:
        lines.append(f"        {m}::SLUG,")
    lines += ["    ]", "}", ""]
    (GEN_DIR / "mod.rs").write_text("\n".join(lines), encoding="utf-8")


def generate(slug: str):
    code = gen_module(slug)
    ident = rust_ident(slug)
    # Each module exports its slug so mod.rs needs no duplicate literal.
    code = code.replace(
        "pub fn screen()",
        f"pub const SLUG: &str = {json.dumps(slug)};\n\npub fn screen()",
        1,
    )
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    path = GEN_DIR / f"{ident}.rs"
    path.write_text(code, encoding="utf-8")
    print(f"generated {path.relative_to(REPO)}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("slug", nargs="?")
    ap.add_argument("--all", action="store_true",
                    help="generate every geometry-bearing capture")
    args = ap.parse_args()

    if args.all:
        n_geo = n_slot = 0
        for p in sorted(CAPTURES.glob("*.json")):
            if p.name.endswith(".render.json"):
                continue
            d = json.loads(p.read_text())
            if not isinstance(d, dict) or "areas" not in d:
                continue
            if geometry_bearing(d):
                generate(p.stem)
                n_geo += 1
            else:
                n_slot += 1
        regen_mod_rs()
        print(f"{n_geo} screen(s) generated; {n_slot} slot-only capture(s) "
              "skipped (setup-fn traces, no widgets).")
    elif args.slug:
        generate(args.slug)
        regen_mod_rs()
    else:
        ap.error("pass a capture slug or --all")


if __name__ == "__main__":
    main()
